name: CI/CD - Testes

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:
    name: Executar testes
    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: npm test

  deploy:
    name: Simular Deploy
    runs-on: ubuntu-latest

    needs: test

    steps:

      - name: Simular deploy
        run: echo "Deploy realizado com sucesso!"